// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: flock.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Broadcast_Type int32

const (
	Broadcast_ANNOUNCE         Broadcast_Type = 0
	Broadcast_ANNOUNCE_REQUEST Broadcast_Type = 1
)

// Enum value maps for Broadcast_Type.
var (
	Broadcast_Type_name = map[int32]string{
		0: "ANNOUNCE",
		1: "ANNOUNCE_REQUEST",
	}
	Broadcast_Type_value = map[string]int32{
		"ANNOUNCE":         0,
		"ANNOUNCE_REQUEST": 1,
	}
)

func (x Broadcast_Type) Enum() *Broadcast_Type {
	p := new(Broadcast_Type)
	*p = x
	return p
}

func (x Broadcast_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Broadcast_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_flock_proto_enumTypes[0].Descriptor()
}

func (Broadcast_Type) Type() protoreflect.EnumType {
	return &file_flock_proto_enumTypes[0]
}

func (x Broadcast_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Broadcast_Type.Descriptor instead.
func (Broadcast_Type) EnumDescriptor() ([]byte, []int) {
	return file_flock_proto_rawDescGZIP(), []int{0, 0}
}

type ShutdownCommand_Mode int32

const (
	ShutdownCommand_POWER_OFF ShutdownCommand_Mode = 0
	ShutdownCommand_SLEEP     ShutdownCommand_Mode = 1
)

// Enum value maps for ShutdownCommand_Mode.
var (
	ShutdownCommand_Mode_name = map[int32]string{
		0: "POWER_OFF",
		1: "SLEEP",
	}
	ShutdownCommand_Mode_value = map[string]int32{
		"POWER_OFF": 0,
		"SLEEP":     1,
	}
)

func (x ShutdownCommand_Mode) Enum() *ShutdownCommand_Mode {
	p := new(ShutdownCommand_Mode)
	*p = x
	return p
}

func (x ShutdownCommand_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShutdownCommand_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_flock_proto_enumTypes[1].Descriptor()
}

func (ShutdownCommand_Mode) Type() protoreflect.EnumType {
	return &file_flock_proto_enumTypes[1]
}

func (x ShutdownCommand_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShutdownCommand_Mode.Descriptor instead.
func (ShutdownCommand_Mode) EnumDescriptor() ([]byte, []int) {
	return file_flock_proto_rawDescGZIP(), []int{4, 0}
}

type Broadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Broadcast_Type `protobuf:"varint,1,opt,name=type,proto3,enum=messages.Broadcast_Type" json:"type,omitempty"`
	// Types that are assignable to Message:
	//	*Broadcast_Announce
	//	*Broadcast_AnnounceRequest
	Message isBroadcast_Message `protobuf_oneof:"message"`
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_flock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_flock_proto_rawDescGZIP(), []int{0}
}

func (x *Broadcast) GetType() Broadcast_Type {
	if x != nil {
		return x.Type
	}
	return Broadcast_ANNOUNCE
}

func (m *Broadcast) GetMessage() isBroadcast_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Broadcast) GetAnnounce() *Announce {
	if x, ok := x.GetMessage().(*Broadcast_Announce); ok {
		return x.Announce
	}
	return nil
}

func (x *Broadcast) GetAnnounceRequest() *AnnounceRequest {
	if x, ok := x.GetMessage().(*Broadcast_AnnounceRequest); ok {
		return x.AnnounceRequest
	}
	return nil
}

type isBroadcast_Message interface {
	isBroadcast_Message()
}

type Broadcast_Announce struct {
	Announce *Announce `protobuf:"bytes,2,opt,name=announce,proto3,oneof"`
}

type Broadcast_AnnounceRequest struct {
	AnnounceRequest *AnnounceRequest `protobuf:"bytes,3,opt,name=announce_request,json=announceRequest,proto3,oneof"`
}

func (*Broadcast_Announce) isBroadcast_Message() {}

func (*Broadcast_AnnounceRequest) isBroadcast_Message() {}

type Announce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Interface string `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	HwAddr    string `protobuf:"bytes,3,opt,name=hw_addr,json=hwAddr,proto3" json:"hw_addr,omitempty"`
	IpAddr    string `protobuf:"bytes,4,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"`
	Netmask   string `protobuf:"bytes,5,opt,name=netmask,proto3" json:"netmask,omitempty"`
}

func (x *Announce) Reset() {
	*x = Announce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Announce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announce) ProtoMessage() {}

func (x *Announce) ProtoReflect() protoreflect.Message {
	mi := &file_flock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announce.ProtoReflect.Descriptor instead.
func (*Announce) Descriptor() ([]byte, []int) {
	return file_flock_proto_rawDescGZIP(), []int{1}
}

func (x *Announce) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Announce) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Announce) GetHwAddr() string {
	if x != nil {
		return x.HwAddr
	}
	return ""
}

func (x *Announce) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *Announce) GetNetmask() string {
	if x != nil {
		return x.Netmask
	}
	return ""
}

type AnnounceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AnnounceRequest) Reset() {
	*x = AnnounceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flock_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceRequest) ProtoMessage() {}

func (x *AnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flock_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceRequest.ProtoReflect.Descriptor instead.
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return file_flock_proto_rawDescGZIP(), []int{2}
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//	*Command_Shutdown
	Command isCommand_Command `protobuf_oneof:"command"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flock_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_flock_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_flock_proto_rawDescGZIP(), []int{3}
}

func (m *Command) GetCommand() isCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *Command) GetShutdown() *ShutdownCommand {
	if x, ok := x.GetCommand().(*Command_Shutdown); ok {
		return x.Shutdown
	}
	return nil
}

type isCommand_Command interface {
	isCommand_Command()
}

type Command_Shutdown struct {
	Shutdown *ShutdownCommand `protobuf:"bytes,1,opt,name=shutdown,proto3,oneof"`
}

func (*Command_Shutdown) isCommand_Command() {}

type ShutdownCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode ShutdownCommand_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=messages.ShutdownCommand_Mode" json:"mode,omitempty"`
}

func (x *ShutdownCommand) Reset() {
	*x = ShutdownCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flock_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownCommand) ProtoMessage() {}

func (x *ShutdownCommand) ProtoReflect() protoreflect.Message {
	mi := &file_flock_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownCommand.ProtoReflect.Descriptor instead.
func (*ShutdownCommand) Descriptor() ([]byte, []int) {
	return file_flock_proto_rawDescGZIP(), []int{4}
}

func (x *ShutdownCommand) GetMode() ShutdownCommand_Mode {
	if x != nil {
		return x.Mode
	}
	return ShutdownCommand_POWER_OFF
}

var File_flock_proto protoreflect.FileDescriptor

var file_flock_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xea, 0x01, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x08, 0x61, 0x6e, 0x6e,
	0x6f, 0x75, 0x6e, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x61, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x4e, 0x4e, 0x4f, 0x55, 0x4e, 0x43,
	0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x4e, 0x4e, 0x4f, 0x55, 0x4e, 0x43, 0x45, 0x5f,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x08, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x77, 0x41, 0x64, 0x64, 0x72, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x6d, 0x61, 0x73, 0x6b,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x6d, 0x61, 0x73, 0x6b, 0x22,
	0x11, 0x0a, 0x0f, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x4d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x37, 0x0a,
	0x08, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64,
	0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x08, 0x73, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x22, 0x67, 0x0a, 0x0f, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x32, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x20, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x0d, 0x0a, 0x09, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x53, 0x4c, 0x45, 0x45, 0x50, 0x10, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flock_proto_rawDescOnce sync.Once
	file_flock_proto_rawDescData = file_flock_proto_rawDesc
)

func file_flock_proto_rawDescGZIP() []byte {
	file_flock_proto_rawDescOnce.Do(func() {
		file_flock_proto_rawDescData = protoimpl.X.CompressGZIP(file_flock_proto_rawDescData)
	})
	return file_flock_proto_rawDescData
}

var file_flock_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_flock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_flock_proto_goTypes = []interface{}{
	(Broadcast_Type)(0),       // 0: messages.Broadcast.Type
	(ShutdownCommand_Mode)(0), // 1: messages.ShutdownCommand.Mode
	(*Broadcast)(nil),         // 2: messages.Broadcast
	(*Announce)(nil),          // 3: messages.Announce
	(*AnnounceRequest)(nil),   // 4: messages.AnnounceRequest
	(*Command)(nil),           // 5: messages.Command
	(*ShutdownCommand)(nil),   // 6: messages.ShutdownCommand
}
var file_flock_proto_depIdxs = []int32{
	0, // 0: messages.Broadcast.type:type_name -> messages.Broadcast.Type
	3, // 1: messages.Broadcast.announce:type_name -> messages.Announce
	4, // 2: messages.Broadcast.announce_request:type_name -> messages.AnnounceRequest
	6, // 3: messages.Command.shutdown:type_name -> messages.ShutdownCommand
	1, // 4: messages.ShutdownCommand.mode:type_name -> messages.ShutdownCommand.Mode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_flock_proto_init() }
func file_flock_proto_init() {
	if File_flock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Broadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Announce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flock_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnounceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flock_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flock_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_flock_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Broadcast_Announce)(nil),
		(*Broadcast_AnnounceRequest)(nil),
	}
	file_flock_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Command_Shutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flock_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flock_proto_goTypes,
		DependencyIndexes: file_flock_proto_depIdxs,
		EnumInfos:         file_flock_proto_enumTypes,
		MessageInfos:      file_flock_proto_msgTypes,
	}.Build()
	File_flock_proto = out.File
	file_flock_proto_rawDesc = nil
	file_flock_proto_goTypes = nil
	file_flock_proto_depIdxs = nil
}
